/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import lsi.us.es.mis.xtext.services.MyPricingDslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import pricing.AddOn;
import pricing.Feature;
import pricing.NonRenewable;
import pricing.Period;
import pricing.Plan;
import pricing.Pricing;
import pricing.PricingPackage;
import pricing.Renewable;

@SuppressWarnings("all")
public class MyPricingDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyPricingDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PricingPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PricingPackage.ADD_ON:
				sequence_AddOn(context, (AddOn) semanticObject); 
				return; 
			case PricingPackage.FEATURE:
				sequence_Feature(context, (Feature) semanticObject); 
				return; 
			case PricingPackage.NON_RENEWABLE:
				sequence_NonRenewable(context, (NonRenewable) semanticObject); 
				return; 
			case PricingPackage.PERIOD:
				sequence_Period(context, (Period) semanticObject); 
				return; 
			case PricingPackage.PLAN:
				sequence_Plan(context, (Plan) semanticObject); 
				return; 
			case PricingPackage.PRICING:
				sequence_Pricing(context, (Pricing) semanticObject); 
				return; 
			case PricingPackage.RENEWABLE:
				sequence_Renewable(context, (Renewable) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     AddOn returns AddOn
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         price=EDouble? 
	 *         (usageLimits+=[UsageLimit|EString] usageLimits+=[UsageLimit|EString]*)? 
	 *         (availableFor+=[Plan|EString] availableFor+=[Plan|EString]*)? 
	 *         (dependsOn+=[AddOn|EString] dependsOn+=[AddOn|EString]*)? 
	 *         (excludes+=[AddOn|EString] excludes+=[AddOn|EString]*)? 
	 *         (features+=Feature features+=Feature*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_AddOn(ISerializationContext context, AddOn semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Feature returns Feature
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         description=EString? 
	 *         value=EString? 
	 *         expression=EString? 
	 *         serverExpression=EString? 
	 *         defaultValue=EString? 
	 *         valueType=ValueType?
	 *     )
	 * </pre>
	 */
	protected void sequence_Feature(ISerializationContext context, Feature semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UsageLimit returns NonRenewable
	 *     NonRenewable returns NonRenewable
	 *
	 * Constraint:
	 *     (
	 *         trackable?='trackable'? 
	 *         name=EString 
	 *         value=EString? 
	 *         defaultValue=EString? 
	 *         description=EString? 
	 *         unit=EString? 
	 *         valueType=ValueType? 
	 *         limit=EDouble? 
	 *         (linkedTo+=[Feature|EString] linkedTo+=[Feature|EString]*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_NonRenewable(ISerializationContext context, NonRenewable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Period returns Period
	 *
	 * Constraint:
	 *     (value=EInt? unit=TimeUnit?)
	 * </pre>
	 */
	protected void sequence_Period(ISerializationContext context, Period semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Plan returns Plan
	 *
	 * Constraint:
	 *     (name=EString description=EString? price=EDouble? (features+=Feature features+=Feature*)? (usageLimits+=UsageLimit usageLimits+=UsageLimit*)?)
	 * </pre>
	 */
	protected void sequence_Plan(ISerializationContext context, Plan semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Pricing returns Pricing
	 *
	 * Constraint:
	 *     (
	 *         saasName=EString? 
	 *         version=EString? 
	 *         currency=EString? 
	 *         url=EString? 
	 *         createdAt=EString? 
	 *         plans+=Plan* 
	 *         addOns+=AddOn*
	 *     )
	 * </pre>
	 */
	protected void sequence_Pricing(ISerializationContext context, Pricing semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UsageLimit returns Renewable
	 *     Renewable returns Renewable
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         value=EString? 
	 *         defaultValue=EString? 
	 *         description=EString? 
	 *         unit=EString? 
	 *         valueType=ValueType? 
	 *         limit=EDouble? 
	 *         (linkedTo+=[Feature|EString] linkedTo+=[Feature|EString]*)? 
	 *         period=Period
	 *     )
	 * </pre>
	 */
	protected void sequence_Renewable(ISerializationContext context, Renewable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
