#

pluginName = lsi.us.es.mis.pricing Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Pricing_type = Pricing
_UI_Plan_type = Plan
_UI_AddOn_type = Add On
_UI_Feature_type = Feature
_UI_UsageLimit_type = Usage Limit
_UI_Period_type = Period
_UI_Renewable_type = Renewable
_UI_NonRenewable_type = Non Renewable
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Pricing_saasName_feature = Saas Name
_UI_Pricing_version_feature = Version
_UI_Pricing_currency_feature = Currency
_UI_Pricing_url_feature = Url
_UI_Pricing_createdAt_feature = Created At
_UI_Pricing_tags_feature = Tags
_UI_Pricing_plans_feature = Plans
_UI_Pricing_addOns_feature = Add Ons
_UI_Plan_name_feature = Name
_UI_Plan_description_feature = Description
_UI_Plan_price_feature = Price
_UI_Plan_features_feature = Features
_UI_Plan_usageLimits_feature = Usage Limits
_UI_AddOn_name_feature = Name
_UI_AddOn_description_feature = Description
_UI_AddOn_price_feature = Price
_UI_AddOn_features_feature = Features
_UI_AddOn_usageLimits_feature = Usage Limits
_UI_AddOn_availableFor_feature = Available For
_UI_AddOn_dependsOn_feature = Depends On
_UI_AddOn_excludes_feature = Excludes
_UI_Feature_name_feature = Name
_UI_Feature_description_feature = Description
_UI_Feature_value_feature = Value
_UI_Feature_expression_feature = Expression
_UI_Feature_serverExpression_feature = Server Expression
_UI_Feature_defaultValue_feature = Default Value
_UI_Feature_valueType_feature = Value Type
_UI_UsageLimit_value_feature = Value
_UI_UsageLimit_defaultValue_feature = Default Value
_UI_UsageLimit_name_feature = Name
_UI_UsageLimit_description_feature = Description
_UI_UsageLimit_unit_feature = Unit
_UI_UsageLimit_valueType_feature = Value Type
_UI_UsageLimit_limit_feature = Limit
_UI_UsageLimit_linkedTo_feature = Linked To
_UI_Period_value_feature = Value
_UI_Period_unit_feature = Unit
_UI_Renewable_period_feature = Period
_UI_NonRenewable_trackable_feature = Trackable
_UI_Unknown_feature = Unspecified

_UI_ValueType_NUMERIC_literal = NUMERIC
_UI_ValueType_BOOLEAN_literal = BOOLEAN
_UI_ValueType_TEXT_literal = TEXT
_UI_TimeUnit_SEC_literal = SEC
_UI_TimeUnit_MIN_literal = MIN
_UI_TimeUnit_HOUR_literal = HOUR
_UI_TimeUnit_DAY_literal = DAY
_UI_TimeUnit_MONTH_literal = MONTH
_UI_TimeUnit_YEAR_literal = YEAR
