/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import lsi.us.es.mis.xtext.MyPricingDslRuntimeModule;
import lsi.us.es.mis.xtext.MyPricingDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyPricingDslIdeSetup extends MyPricingDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyPricingDslRuntimeModule(), new MyPricingDslIdeModule()));
	}
	
}
