/**
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import lsi.us.es.mis.xtext.services.MyPricingDslGrammarAccess;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import pricing.AddOn;
import pricing.Feature;
import pricing.Plan;
import pricing.Pricing;

@SuppressWarnings("all")
public class MyPricingDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyPricingDslGrammarAccess _myPricingDslGrammarAccess;

  protected void _format(final Pricing pricing, @Extension final IFormattableDocument document) {
    EList<Plan> _plans = pricing.getPlans();
    for (final Plan plan : _plans) {
      document.<Plan>format(plan);
    }
    EList<AddOn> _addOns = pricing.getAddOns();
    for (final AddOn addOn : _addOns) {
      document.<AddOn>format(addOn);
    }
  }

  protected void _format(final AddOn addOn, @Extension final IFormattableDocument document) {
    EList<Feature> _features = addOn.getFeatures();
    for (final Feature feature : _features) {
      document.<Feature>format(feature);
    }
  }

  public void format(final Object addOn, final IFormattableDocument document) {
    if (addOn instanceof XtextResource) {
      _format((XtextResource)addOn, document);
      return;
    } else if (addOn instanceof AddOn) {
      _format((AddOn)addOn, document);
      return;
    } else if (addOn instanceof Pricing) {
      _format((Pricing)addOn, document);
      return;
    } else if (addOn instanceof EObject) {
      _format((EObject)addOn, document);
      return;
    } else if (addOn == null) {
      _format((Void)null, document);
      return;
    } else if (addOn != null) {
      _format(addOn, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(addOn, document).toString());
    }
  }
}
