/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import lsi.us.es.mis.xtext.ide.contentassist.antlr.internal.InternalMyPricingDslParser;
import lsi.us.es.mis.xtext.services.MyPricingDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MyPricingDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyPricingDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyPricingDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUsageLimitAccess().getAlternatives(), "rule__UsageLimit__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getValueTypeAccess().getAlternatives(), "rule__ValueType__Alternatives");
			builder.put(grammarAccess.getTimeUnitAccess().getAlternatives(), "rule__TimeUnit__Alternatives");
			builder.put(grammarAccess.getPricingAccess().getGroup(), "rule__Pricing__Group__0");
			builder.put(grammarAccess.getPricingAccess().getGroup_3(), "rule__Pricing__Group_3__0");
			builder.put(grammarAccess.getPricingAccess().getGroup_4(), "rule__Pricing__Group_4__0");
			builder.put(grammarAccess.getPricingAccess().getGroup_5(), "rule__Pricing__Group_5__0");
			builder.put(grammarAccess.getPricingAccess().getGroup_6(), "rule__Pricing__Group_6__0");
			builder.put(grammarAccess.getPricingAccess().getGroup_7(), "rule__Pricing__Group_7__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup(), "rule__AddOn__Group__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_4(), "rule__AddOn__Group_4__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_5(), "rule__AddOn__Group_5__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_6(), "rule__AddOn__Group_6__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_6_3(), "rule__AddOn__Group_6_3__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_7(), "rule__AddOn__Group_7__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_7_3(), "rule__AddOn__Group_7_3__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_8(), "rule__AddOn__Group_8__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_8_3(), "rule__AddOn__Group_8_3__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_9(), "rule__AddOn__Group_9__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_9_3(), "rule__AddOn__Group_9_3__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_10(), "rule__AddOn__Group_10__0");
			builder.put(grammarAccess.getAddOnAccess().getGroup_10_3(), "rule__AddOn__Group_10_3__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup(), "rule__Feature__Group__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_4(), "rule__Feature__Group_4__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_5(), "rule__Feature__Group_5__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_6(), "rule__Feature__Group_6__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_7(), "rule__Feature__Group_7__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_8(), "rule__Feature__Group_8__0");
			builder.put(grammarAccess.getFeatureAccess().getGroup_9(), "rule__Feature__Group_9__0");
			builder.put(grammarAccess.getPlanAccess().getGroup(), "rule__Plan__Group__0");
			builder.put(grammarAccess.getPlanAccess().getGroup_4(), "rule__Plan__Group_4__0");
			builder.put(grammarAccess.getPlanAccess().getGroup_5(), "rule__Plan__Group_5__0");
			builder.put(grammarAccess.getPlanAccess().getGroup_6(), "rule__Plan__Group_6__0");
			builder.put(grammarAccess.getPlanAccess().getGroup_6_3(), "rule__Plan__Group_6_3__0");
			builder.put(grammarAccess.getPlanAccess().getGroup_7(), "rule__Plan__Group_7__0");
			builder.put(grammarAccess.getPlanAccess().getGroup_7_3(), "rule__Plan__Group_7_3__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup(), "rule__Renewable__Group__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_4(), "rule__Renewable__Group_4__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_5(), "rule__Renewable__Group_5__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_6(), "rule__Renewable__Group_6__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_7(), "rule__Renewable__Group_7__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_8(), "rule__Renewable__Group_8__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_9(), "rule__Renewable__Group_9__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_10(), "rule__Renewable__Group_10__0");
			builder.put(grammarAccess.getRenewableAccess().getGroup_10_3(), "rule__Renewable__Group_10_3__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup(), "rule__NonRenewable__Group__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_5(), "rule__NonRenewable__Group_5__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_6(), "rule__NonRenewable__Group_6__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_7(), "rule__NonRenewable__Group_7__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_8(), "rule__NonRenewable__Group_8__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_9(), "rule__NonRenewable__Group_9__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_10(), "rule__NonRenewable__Group_10__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_11(), "rule__NonRenewable__Group_11__0");
			builder.put(grammarAccess.getNonRenewableAccess().getGroup_11_3(), "rule__NonRenewable__Group_11_3__0");
			builder.put(grammarAccess.getPeriodAccess().getGroup(), "rule__Period__Group__0");
			builder.put(grammarAccess.getPeriodAccess().getGroup_3(), "rule__Period__Group_3__0");
			builder.put(grammarAccess.getPeriodAccess().getGroup_4(), "rule__Period__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getPricingAccess().getSaasNameAssignment_3_1(), "rule__Pricing__SaasNameAssignment_3_1");
			builder.put(grammarAccess.getPricingAccess().getVersionAssignment_4_1(), "rule__Pricing__VersionAssignment_4_1");
			builder.put(grammarAccess.getPricingAccess().getCurrencyAssignment_5_1(), "rule__Pricing__CurrencyAssignment_5_1");
			builder.put(grammarAccess.getPricingAccess().getUrlAssignment_6_1(), "rule__Pricing__UrlAssignment_6_1");
			builder.put(grammarAccess.getPricingAccess().getCreatedAtAssignment_7_1(), "rule__Pricing__CreatedAtAssignment_7_1");
			builder.put(grammarAccess.getPricingAccess().getPlansAssignment_8(), "rule__Pricing__PlansAssignment_8");
			builder.put(grammarAccess.getPricingAccess().getAddOnsAssignment_9(), "rule__Pricing__AddOnsAssignment_9");
			builder.put(grammarAccess.getAddOnAccess().getNameAssignment_2(), "rule__AddOn__NameAssignment_2");
			builder.put(grammarAccess.getAddOnAccess().getDescriptionAssignment_4_1(), "rule__AddOn__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAddOnAccess().getPriceAssignment_5_1(), "rule__AddOn__PriceAssignment_5_1");
			builder.put(grammarAccess.getAddOnAccess().getUsageLimitsAssignment_6_2(), "rule__AddOn__UsageLimitsAssignment_6_2");
			builder.put(grammarAccess.getAddOnAccess().getUsageLimitsAssignment_6_3_1(), "rule__AddOn__UsageLimitsAssignment_6_3_1");
			builder.put(grammarAccess.getAddOnAccess().getAvailableForAssignment_7_2(), "rule__AddOn__AvailableForAssignment_7_2");
			builder.put(grammarAccess.getAddOnAccess().getAvailableForAssignment_7_3_1(), "rule__AddOn__AvailableForAssignment_7_3_1");
			builder.put(grammarAccess.getAddOnAccess().getDependsOnAssignment_8_2(), "rule__AddOn__DependsOnAssignment_8_2");
			builder.put(grammarAccess.getAddOnAccess().getDependsOnAssignment_8_3_1(), "rule__AddOn__DependsOnAssignment_8_3_1");
			builder.put(grammarAccess.getAddOnAccess().getExcludesAssignment_9_2(), "rule__AddOn__ExcludesAssignment_9_2");
			builder.put(grammarAccess.getAddOnAccess().getExcludesAssignment_9_3_1(), "rule__AddOn__ExcludesAssignment_9_3_1");
			builder.put(grammarAccess.getAddOnAccess().getFeaturesAssignment_10_2(), "rule__AddOn__FeaturesAssignment_10_2");
			builder.put(grammarAccess.getAddOnAccess().getFeaturesAssignment_10_3_1(), "rule__AddOn__FeaturesAssignment_10_3_1");
			builder.put(grammarAccess.getFeatureAccess().getNameAssignment_2(), "rule__Feature__NameAssignment_2");
			builder.put(grammarAccess.getFeatureAccess().getDescriptionAssignment_4_1(), "rule__Feature__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getFeatureAccess().getValueAssignment_5_1(), "rule__Feature__ValueAssignment_5_1");
			builder.put(grammarAccess.getFeatureAccess().getExpressionAssignment_6_1(), "rule__Feature__ExpressionAssignment_6_1");
			builder.put(grammarAccess.getFeatureAccess().getServerExpressionAssignment_7_1(), "rule__Feature__ServerExpressionAssignment_7_1");
			builder.put(grammarAccess.getFeatureAccess().getDefaultValueAssignment_8_1(), "rule__Feature__DefaultValueAssignment_8_1");
			builder.put(grammarAccess.getFeatureAccess().getValueTypeAssignment_9_1(), "rule__Feature__ValueTypeAssignment_9_1");
			builder.put(grammarAccess.getPlanAccess().getNameAssignment_2(), "rule__Plan__NameAssignment_2");
			builder.put(grammarAccess.getPlanAccess().getDescriptionAssignment_4_1(), "rule__Plan__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getPlanAccess().getPriceAssignment_5_1(), "rule__Plan__PriceAssignment_5_1");
			builder.put(grammarAccess.getPlanAccess().getFeaturesAssignment_6_2(), "rule__Plan__FeaturesAssignment_6_2");
			builder.put(grammarAccess.getPlanAccess().getFeaturesAssignment_6_3_1(), "rule__Plan__FeaturesAssignment_6_3_1");
			builder.put(grammarAccess.getPlanAccess().getUsageLimitsAssignment_7_2(), "rule__Plan__UsageLimitsAssignment_7_2");
			builder.put(grammarAccess.getPlanAccess().getUsageLimitsAssignment_7_3_1(), "rule__Plan__UsageLimitsAssignment_7_3_1");
			builder.put(grammarAccess.getRenewableAccess().getNameAssignment_2(), "rule__Renewable__NameAssignment_2");
			builder.put(grammarAccess.getRenewableAccess().getValueAssignment_4_1(), "rule__Renewable__ValueAssignment_4_1");
			builder.put(grammarAccess.getRenewableAccess().getDefaultValueAssignment_5_1(), "rule__Renewable__DefaultValueAssignment_5_1");
			builder.put(grammarAccess.getRenewableAccess().getDescriptionAssignment_6_1(), "rule__Renewable__DescriptionAssignment_6_1");
			builder.put(grammarAccess.getRenewableAccess().getUnitAssignment_7_1(), "rule__Renewable__UnitAssignment_7_1");
			builder.put(grammarAccess.getRenewableAccess().getValueTypeAssignment_8_1(), "rule__Renewable__ValueTypeAssignment_8_1");
			builder.put(grammarAccess.getRenewableAccess().getLimitAssignment_9_1(), "rule__Renewable__LimitAssignment_9_1");
			builder.put(grammarAccess.getRenewableAccess().getLinkedToAssignment_10_2(), "rule__Renewable__LinkedToAssignment_10_2");
			builder.put(grammarAccess.getRenewableAccess().getLinkedToAssignment_10_3_1(), "rule__Renewable__LinkedToAssignment_10_3_1");
			builder.put(grammarAccess.getRenewableAccess().getPeriodAssignment_12(), "rule__Renewable__PeriodAssignment_12");
			builder.put(grammarAccess.getNonRenewableAccess().getTrackableAssignment_1(), "rule__NonRenewable__TrackableAssignment_1");
			builder.put(grammarAccess.getNonRenewableAccess().getNameAssignment_3(), "rule__NonRenewable__NameAssignment_3");
			builder.put(grammarAccess.getNonRenewableAccess().getValueAssignment_5_1(), "rule__NonRenewable__ValueAssignment_5_1");
			builder.put(grammarAccess.getNonRenewableAccess().getDefaultValueAssignment_6_1(), "rule__NonRenewable__DefaultValueAssignment_6_1");
			builder.put(grammarAccess.getNonRenewableAccess().getDescriptionAssignment_7_1(), "rule__NonRenewable__DescriptionAssignment_7_1");
			builder.put(grammarAccess.getNonRenewableAccess().getUnitAssignment_8_1(), "rule__NonRenewable__UnitAssignment_8_1");
			builder.put(grammarAccess.getNonRenewableAccess().getValueTypeAssignment_9_1(), "rule__NonRenewable__ValueTypeAssignment_9_1");
			builder.put(grammarAccess.getNonRenewableAccess().getLimitAssignment_10_1(), "rule__NonRenewable__LimitAssignment_10_1");
			builder.put(grammarAccess.getNonRenewableAccess().getLinkedToAssignment_11_2(), "rule__NonRenewable__LinkedToAssignment_11_2");
			builder.put(grammarAccess.getNonRenewableAccess().getLinkedToAssignment_11_3_1(), "rule__NonRenewable__LinkedToAssignment_11_3_1");
			builder.put(grammarAccess.getPeriodAccess().getValueAssignment_3_1(), "rule__Period__ValueAssignment_3_1");
			builder.put(grammarAccess.getPeriodAccess().getUnitAssignment_4_1(), "rule__Period__UnitAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyPricingDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyPricingDslParser createParser() {
		InternalMyPricingDslParser result = new InternalMyPricingDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyPricingDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyPricingDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
