/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.formatting2

import com.google.inject.Inject
import lsi.us.es.mis.xtext.services.MyPricingDslGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import pricing.AddOn
import pricing.Pricing

class MyPricingDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyPricingDslGrammarAccess

	def dispatch void format(Pricing pricing, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (plan : pricing.plans) {
			plan.format
		}
		for (addOn : pricing.addOns) {
			addOn.format
		}
	}

	def dispatch void format(AddOn addOn, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (feature : addOn.features) {
			feature.format
		}
	}
	
	// TODO: implement for Plan, Renewable
}
