/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyPricingDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class PricingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.Pricing");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPricingAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPricingKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cSaasNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cSaasNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cSaasNameEStringParserRuleCall_3_1_0 = (RuleCall)cSaasNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVersionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVersionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVersionEStringParserRuleCall_4_1_0 = (RuleCall)cVersionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCurrencyKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCurrencyAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCurrencyEStringParserRuleCall_5_1_0 = (RuleCall)cCurrencyAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cUrlKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cUrlAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cUrlEStringParserRuleCall_6_1_0 = (RuleCall)cUrlAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCreatedAtKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCreatedAtAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cCreatedAtEStringParserRuleCall_7_1_0 = (RuleCall)cCreatedAtAssignment_7_1.eContents().get(0);
		private final Assignment cPlansAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPlansPlanParserRuleCall_8_0 = (RuleCall)cPlansAssignment_8.eContents().get(0);
		private final Assignment cAddOnsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cAddOnsAddOnParserRuleCall_9_0 = (RuleCall)cAddOnsAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Pricing returns Pricing:
		//    {Pricing}
		//    'Pricing'
		//    '{'
		//        ('saasName' saasName=EString)?
		//        ('version' version=EString)?
		//        ('currency' currency=EString)?
		//        ('url' url=EString)?
		//        ('createdAt' createdAt=EString)?
		//        (plans+=Plan)*
		//        (addOns+=AddOn)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Pricing}
		//'Pricing'
		//'{'
		//    ('saasName' saasName=EString)?
		//    ('version' version=EString)?
		//    ('currency' currency=EString)?
		//    ('url' url=EString)?
		//    ('createdAt' createdAt=EString)?
		//    (plans+=Plan)*
		//    (addOns+=AddOn)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Pricing}
		public Action getPricingAction_0() { return cPricingAction_0; }
		
		//'Pricing'
		public Keyword getPricingKeyword_1() { return cPricingKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('saasName' saasName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'saasName'
		public Keyword getSaasNameKeyword_3_0() { return cSaasNameKeyword_3_0; }
		
		//saasName=EString
		public Assignment getSaasNameAssignment_3_1() { return cSaasNameAssignment_3_1; }
		
		//EString
		public RuleCall getSaasNameEStringParserRuleCall_3_1_0() { return cSaasNameEStringParserRuleCall_3_1_0; }
		
		//('version' version=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'version'
		public Keyword getVersionKeyword_4_0() { return cVersionKeyword_4_0; }
		
		//version=EString
		public Assignment getVersionAssignment_4_1() { return cVersionAssignment_4_1; }
		
		//EString
		public RuleCall getVersionEStringParserRuleCall_4_1_0() { return cVersionEStringParserRuleCall_4_1_0; }
		
		//('currency' currency=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'currency'
		public Keyword getCurrencyKeyword_5_0() { return cCurrencyKeyword_5_0; }
		
		//currency=EString
		public Assignment getCurrencyAssignment_5_1() { return cCurrencyAssignment_5_1; }
		
		//EString
		public RuleCall getCurrencyEStringParserRuleCall_5_1_0() { return cCurrencyEStringParserRuleCall_5_1_0; }
		
		//('url' url=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'url'
		public Keyword getUrlKeyword_6_0() { return cUrlKeyword_6_0; }
		
		//url=EString
		public Assignment getUrlAssignment_6_1() { return cUrlAssignment_6_1; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_6_1_0() { return cUrlEStringParserRuleCall_6_1_0; }
		
		//('createdAt' createdAt=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'createdAt'
		public Keyword getCreatedAtKeyword_7_0() { return cCreatedAtKeyword_7_0; }
		
		//createdAt=EString
		public Assignment getCreatedAtAssignment_7_1() { return cCreatedAtAssignment_7_1; }
		
		//EString
		public RuleCall getCreatedAtEStringParserRuleCall_7_1_0() { return cCreatedAtEStringParserRuleCall_7_1_0; }
		
		//(plans+=Plan)*
		public Assignment getPlansAssignment_8() { return cPlansAssignment_8; }
		
		//Plan
		public RuleCall getPlansPlanParserRuleCall_8_0() { return cPlansPlanParserRuleCall_8_0; }
		
		//(addOns+=AddOn)*
		public Assignment getAddOnsAssignment_9() { return cAddOnsAssignment_9; }
		
		//AddOn
		public RuleCall getAddOnsAddOnParserRuleCall_9_0() { return cAddOnsAddOnParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class AddOnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.AddOn");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAddOnAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAddOnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPriceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPriceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPriceEDoubleParserRuleCall_5_1_0 = (RuleCall)cPriceAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cUsageLimitsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cUsageLimitsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cUsageLimitsUsageLimitCrossReference_6_2_0 = (CrossReference)cUsageLimitsAssignment_6_2.eContents().get(0);
		private final RuleCall cUsageLimitsUsageLimitEStringParserRuleCall_6_2_0_1 = (RuleCall)cUsageLimitsUsageLimitCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cUsageLimitsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cUsageLimitsUsageLimitCrossReference_6_3_1_0 = (CrossReference)cUsageLimitsAssignment_6_3_1.eContents().get(0);
		private final RuleCall cUsageLimitsUsageLimitEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cUsageLimitsUsageLimitCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAvailableForKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cAvailableForAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final CrossReference cAvailableForPlanCrossReference_7_2_0 = (CrossReference)cAvailableForAssignment_7_2.eContents().get(0);
		private final RuleCall cAvailableForPlanEStringParserRuleCall_7_2_0_1 = (RuleCall)cAvailableForPlanCrossReference_7_2_0.eContents().get(1);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cAvailableForAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final CrossReference cAvailableForPlanCrossReference_7_3_1_0 = (CrossReference)cAvailableForAssignment_7_3_1.eContents().get(0);
		private final RuleCall cAvailableForPlanEStringParserRuleCall_7_3_1_0_1 = (RuleCall)cAvailableForPlanCrossReference_7_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDependsOnKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cDependsOnAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final CrossReference cDependsOnAddOnCrossReference_8_2_0 = (CrossReference)cDependsOnAssignment_8_2.eContents().get(0);
		private final RuleCall cDependsOnAddOnEStringParserRuleCall_8_2_0_1 = (RuleCall)cDependsOnAddOnCrossReference_8_2_0.eContents().get(1);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cDependsOnAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final CrossReference cDependsOnAddOnCrossReference_8_3_1_0 = (CrossReference)cDependsOnAssignment_8_3_1.eContents().get(0);
		private final RuleCall cDependsOnAddOnEStringParserRuleCall_8_3_1_0_1 = (RuleCall)cDependsOnAddOnCrossReference_8_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cExcludesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cExcludesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final CrossReference cExcludesAddOnCrossReference_9_2_0 = (CrossReference)cExcludesAssignment_9_2.eContents().get(0);
		private final RuleCall cExcludesAddOnEStringParserRuleCall_9_2_0_1 = (RuleCall)cExcludesAddOnCrossReference_9_2_0.eContents().get(1);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cExcludesAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final CrossReference cExcludesAddOnCrossReference_9_3_1_0 = (CrossReference)cExcludesAssignment_9_3_1.eContents().get(0);
		private final RuleCall cExcludesAddOnEStringParserRuleCall_9_3_1_0_1 = (RuleCall)cExcludesAddOnCrossReference_9_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cFeaturesKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cFeaturesAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cFeaturesFeatureParserRuleCall_10_2_0 = (RuleCall)cFeaturesAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cFeaturesAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cFeaturesFeatureParserRuleCall_10_3_1_0 = (RuleCall)cFeaturesAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//AddOn returns AddOn:
		//    {AddOn}
		//    'AddOn'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('price' price=EDouble)?
		//        ('usageLimits' '(' usageLimits+=[UsageLimit|EString] ( "," usageLimits+=[UsageLimit|EString])* ')' )?
		//        ('availableFor' '(' availableFor+=[Plan|EString] ( "," availableFor+=[Plan|EString])* ')' )?
		//        ('dependsOn' '(' dependsOn+=[AddOn|EString] ( "," dependsOn+=[AddOn|EString])* ')' )?
		//        ('excludes' '(' excludes+=[AddOn|EString] ( "," excludes+=[AddOn|EString])* ')' )?
		//        ('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{AddOn}
		//'AddOn'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('price' price=EDouble)?
		//    ('usageLimits' '(' usageLimits+=[UsageLimit|EString] ( "," usageLimits+=[UsageLimit|EString])* ')' )?
		//    ('availableFor' '(' availableFor+=[Plan|EString] ( "," availableFor+=[Plan|EString])* ')' )?
		//    ('dependsOn' '(' dependsOn+=[AddOn|EString] ( "," dependsOn+=[AddOn|EString])* ')' )?
		//    ('excludes' '(' excludes+=[AddOn|EString] ( "," excludes+=[AddOn|EString])* ')' )?
		//    ('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{AddOn}
		public Action getAddOnAction_0() { return cAddOnAction_0; }
		
		//'AddOn'
		public Keyword getAddOnKeyword_1() { return cAddOnKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('price' price=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'price'
		public Keyword getPriceKeyword_5_0() { return cPriceKeyword_5_0; }
		
		//price=EDouble
		public Assignment getPriceAssignment_5_1() { return cPriceAssignment_5_1; }
		
		//EDouble
		public RuleCall getPriceEDoubleParserRuleCall_5_1_0() { return cPriceEDoubleParserRuleCall_5_1_0; }
		
		//('usageLimits' '(' usageLimits+=[UsageLimit|EString] ( "," usageLimits+=[UsageLimit|EString])* ')' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'usageLimits'
		public Keyword getUsageLimitsKeyword_6_0() { return cUsageLimitsKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//usageLimits+=[UsageLimit|EString]
		public Assignment getUsageLimitsAssignment_6_2() { return cUsageLimitsAssignment_6_2; }
		
		//[UsageLimit|EString]
		public CrossReference getUsageLimitsUsageLimitCrossReference_6_2_0() { return cUsageLimitsUsageLimitCrossReference_6_2_0; }
		
		//EString
		public RuleCall getUsageLimitsUsageLimitEStringParserRuleCall_6_2_0_1() { return cUsageLimitsUsageLimitEStringParserRuleCall_6_2_0_1; }
		
		//( "," usageLimits+=[UsageLimit|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//usageLimits+=[UsageLimit|EString]
		public Assignment getUsageLimitsAssignment_6_3_1() { return cUsageLimitsAssignment_6_3_1; }
		
		//[UsageLimit|EString]
		public CrossReference getUsageLimitsUsageLimitCrossReference_6_3_1_0() { return cUsageLimitsUsageLimitCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getUsageLimitsUsageLimitEStringParserRuleCall_6_3_1_0_1() { return cUsageLimitsUsageLimitEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('availableFor' '(' availableFor+=[Plan|EString] ( "," availableFor+=[Plan|EString])* ')' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'availableFor'
		public Keyword getAvailableForKeyword_7_0() { return cAvailableForKeyword_7_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_7_1() { return cLeftParenthesisKeyword_7_1; }
		
		//availableFor+=[Plan|EString]
		public Assignment getAvailableForAssignment_7_2() { return cAvailableForAssignment_7_2; }
		
		//[Plan|EString]
		public CrossReference getAvailableForPlanCrossReference_7_2_0() { return cAvailableForPlanCrossReference_7_2_0; }
		
		//EString
		public RuleCall getAvailableForPlanEStringParserRuleCall_7_2_0_1() { return cAvailableForPlanEStringParserRuleCall_7_2_0_1; }
		
		//( "," availableFor+=[Plan|EString])*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//availableFor+=[Plan|EString]
		public Assignment getAvailableForAssignment_7_3_1() { return cAvailableForAssignment_7_3_1; }
		
		//[Plan|EString]
		public CrossReference getAvailableForPlanCrossReference_7_3_1_0() { return cAvailableForPlanCrossReference_7_3_1_0; }
		
		//EString
		public RuleCall getAvailableForPlanEStringParserRuleCall_7_3_1_0_1() { return cAvailableForPlanEStringParserRuleCall_7_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_4() { return cRightParenthesisKeyword_7_4; }
		
		//('dependsOn' '(' dependsOn+=[AddOn|EString] ( "," dependsOn+=[AddOn|EString])* ')' )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'dependsOn'
		public Keyword getDependsOnKeyword_8_0() { return cDependsOnKeyword_8_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_8_1() { return cLeftParenthesisKeyword_8_1; }
		
		//dependsOn+=[AddOn|EString]
		public Assignment getDependsOnAssignment_8_2() { return cDependsOnAssignment_8_2; }
		
		//[AddOn|EString]
		public CrossReference getDependsOnAddOnCrossReference_8_2_0() { return cDependsOnAddOnCrossReference_8_2_0; }
		
		//EString
		public RuleCall getDependsOnAddOnEStringParserRuleCall_8_2_0_1() { return cDependsOnAddOnEStringParserRuleCall_8_2_0_1; }
		
		//( "," dependsOn+=[AddOn|EString])*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//dependsOn+=[AddOn|EString]
		public Assignment getDependsOnAssignment_8_3_1() { return cDependsOnAssignment_8_3_1; }
		
		//[AddOn|EString]
		public CrossReference getDependsOnAddOnCrossReference_8_3_1_0() { return cDependsOnAddOnCrossReference_8_3_1_0; }
		
		//EString
		public RuleCall getDependsOnAddOnEStringParserRuleCall_8_3_1_0_1() { return cDependsOnAddOnEStringParserRuleCall_8_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8_4() { return cRightParenthesisKeyword_8_4; }
		
		//('excludes' '(' excludes+=[AddOn|EString] ( "," excludes+=[AddOn|EString])* ')' )?
		public Group getGroup_9() { return cGroup_9; }
		
		//'excludes'
		public Keyword getExcludesKeyword_9_0() { return cExcludesKeyword_9_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_9_1() { return cLeftParenthesisKeyword_9_1; }
		
		//excludes+=[AddOn|EString]
		public Assignment getExcludesAssignment_9_2() { return cExcludesAssignment_9_2; }
		
		//[AddOn|EString]
		public CrossReference getExcludesAddOnCrossReference_9_2_0() { return cExcludesAddOnCrossReference_9_2_0; }
		
		//EString
		public RuleCall getExcludesAddOnEStringParserRuleCall_9_2_0_1() { return cExcludesAddOnEStringParserRuleCall_9_2_0_1; }
		
		//( "," excludes+=[AddOn|EString])*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//excludes+=[AddOn|EString]
		public Assignment getExcludesAssignment_9_3_1() { return cExcludesAssignment_9_3_1; }
		
		//[AddOn|EString]
		public CrossReference getExcludesAddOnCrossReference_9_3_1_0() { return cExcludesAddOnCrossReference_9_3_1_0; }
		
		//EString
		public RuleCall getExcludesAddOnEStringParserRuleCall_9_3_1_0_1() { return cExcludesAddOnEStringParserRuleCall_9_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9_4() { return cRightParenthesisKeyword_9_4; }
		
		//('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'features'
		public Keyword getFeaturesKeyword_10_0() { return cFeaturesKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//features+=Feature
		public Assignment getFeaturesAssignment_10_2() { return cFeaturesAssignment_10_2; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_10_2_0() { return cFeaturesFeatureParserRuleCall_10_2_0; }
		
		//( "," features+=Feature)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//features+=Feature
		public Assignment getFeaturesAssignment_10_3_1() { return cFeaturesAssignment_10_3_1; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_10_3_1_0() { return cFeaturesFeatureParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class UsageLimitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.UsageLimit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRenewableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNonRenewableParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//UsageLimit returns UsageLimit:
		//    Renewable | NonRenewable;
		@Override public ParserRule getRule() { return rule; }
		
		//Renewable | NonRenewable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Renewable
		public RuleCall getRenewableParserRuleCall_0() { return cRenewableParserRuleCall_0; }
		
		//NonRenewable
		public RuleCall getNonRenewableParserRuleCall_1() { return cNonRenewableParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFeatureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFeatureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExpressionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cExpressionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cExpressionEStringParserRuleCall_6_1_0 = (RuleCall)cExpressionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cServerExpressionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cServerExpressionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cServerExpressionEStringParserRuleCall_7_1_0 = (RuleCall)cServerExpressionAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDefaultValueKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDefaultValueAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDefaultValueEStringParserRuleCall_8_1_0 = (RuleCall)cDefaultValueAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cValueTypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cValueTypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cValueTypeValueTypeEnumRuleCall_9_1_0 = (RuleCall)cValueTypeAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Feature returns Feature:
		//    {Feature}
		//    'Feature'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('value' value=EString)?
		//        ('expression' expression=EString)?
		//        ('serverExpression' serverExpression=EString)?
		//        ('defaultValue' defaultValue=EString)?
		//        ('valueType' valueType=ValueType)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Feature}
		//'Feature'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('value' value=EString)?
		//    ('expression' expression=EString)?
		//    ('serverExpression' serverExpression=EString)?
		//    ('defaultValue' defaultValue=EString)?
		//    ('valueType' valueType=ValueType)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Feature}
		public Action getFeatureAction_0() { return cFeatureAction_0; }
		
		//'Feature'
		public Keyword getFeatureKeyword_1() { return cFeatureKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('value' value=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'value'
		public Keyword getValueKeyword_5_0() { return cValueKeyword_5_0; }
		
		//value=EString
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_5_1_0() { return cValueEStringParserRuleCall_5_1_0; }
		
		//('expression' expression=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'expression'
		public Keyword getExpressionKeyword_6_0() { return cExpressionKeyword_6_0; }
		
		//expression=EString
		public Assignment getExpressionAssignment_6_1() { return cExpressionAssignment_6_1; }
		
		//EString
		public RuleCall getExpressionEStringParserRuleCall_6_1_0() { return cExpressionEStringParserRuleCall_6_1_0; }
		
		//('serverExpression' serverExpression=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'serverExpression'
		public Keyword getServerExpressionKeyword_7_0() { return cServerExpressionKeyword_7_0; }
		
		//serverExpression=EString
		public Assignment getServerExpressionAssignment_7_1() { return cServerExpressionAssignment_7_1; }
		
		//EString
		public RuleCall getServerExpressionEStringParserRuleCall_7_1_0() { return cServerExpressionEStringParserRuleCall_7_1_0; }
		
		//('defaultValue' defaultValue=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'defaultValue'
		public Keyword getDefaultValueKeyword_8_0() { return cDefaultValueKeyword_8_0; }
		
		//defaultValue=EString
		public Assignment getDefaultValueAssignment_8_1() { return cDefaultValueAssignment_8_1; }
		
		//EString
		public RuleCall getDefaultValueEStringParserRuleCall_8_1_0() { return cDefaultValueEStringParserRuleCall_8_1_0; }
		
		//('valueType' valueType=ValueType)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'valueType'
		public Keyword getValueTypeKeyword_9_0() { return cValueTypeKeyword_9_0; }
		
		//valueType=ValueType
		public Assignment getValueTypeAssignment_9_1() { return cValueTypeAssignment_9_1; }
		
		//ValueType
		public RuleCall getValueTypeValueTypeEnumRuleCall_9_1_0() { return cValueTypeValueTypeEnumRuleCall_9_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class PlanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.Plan");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPlanAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPlanKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPriceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPriceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPriceEDoubleParserRuleCall_5_1_0 = (RuleCall)cPriceAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cFeaturesKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cFeaturesAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cFeaturesFeatureParserRuleCall_6_2_0 = (RuleCall)cFeaturesAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cFeaturesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cFeaturesFeatureParserRuleCall_6_3_1_0 = (RuleCall)cFeaturesAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cUsageLimitsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cUsageLimitsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cUsageLimitsUsageLimitParserRuleCall_7_2_0 = (RuleCall)cUsageLimitsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cUsageLimitsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cUsageLimitsUsageLimitParserRuleCall_7_3_1_0 = (RuleCall)cUsageLimitsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Plan returns Plan:
		//    {Plan}
		//    'Plan'
		//    name=EString
		//    '{'
		//        ('description' description=EString)?
		//        ('price' price=EDouble)?
		//        ('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
		//        ('usageLimits' '{' usageLimits+=UsageLimit ( "," usageLimits+=UsageLimit)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Plan}
		//'Plan'
		//name=EString
		//'{'
		//    ('description' description=EString)?
		//    ('price' price=EDouble)?
		//    ('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
		//    ('usageLimits' '{' usageLimits+=UsageLimit ( "," usageLimits+=UsageLimit)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Plan}
		public Action getPlanAction_0() { return cPlanAction_0; }
		
		//'Plan'
		public Keyword getPlanKeyword_1() { return cPlanKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('price' price=EDouble)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'price'
		public Keyword getPriceKeyword_5_0() { return cPriceKeyword_5_0; }
		
		//price=EDouble
		public Assignment getPriceAssignment_5_1() { return cPriceAssignment_5_1; }
		
		//EDouble
		public RuleCall getPriceEDoubleParserRuleCall_5_1_0() { return cPriceEDoubleParserRuleCall_5_1_0; }
		
		//('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'features'
		public Keyword getFeaturesKeyword_6_0() { return cFeaturesKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//features+=Feature
		public Assignment getFeaturesAssignment_6_2() { return cFeaturesAssignment_6_2; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_6_2_0() { return cFeaturesFeatureParserRuleCall_6_2_0; }
		
		//( "," features+=Feature)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//features+=Feature
		public Assignment getFeaturesAssignment_6_3_1() { return cFeaturesAssignment_6_3_1; }
		
		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_6_3_1_0() { return cFeaturesFeatureParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('usageLimits' '{' usageLimits+=UsageLimit ( "," usageLimits+=UsageLimit)* '}' )?
		public Group getGroup_7() { return cGroup_7; }
		
		//'usageLimits'
		public Keyword getUsageLimitsKeyword_7_0() { return cUsageLimitsKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//usageLimits+=UsageLimit
		public Assignment getUsageLimitsAssignment_7_2() { return cUsageLimitsAssignment_7_2; }
		
		//UsageLimit
		public RuleCall getUsageLimitsUsageLimitParserRuleCall_7_2_0() { return cUsageLimitsUsageLimitParserRuleCall_7_2_0; }
		
		//( "," usageLimits+=UsageLimit)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//usageLimits+=UsageLimit
		public Assignment getUsageLimitsAssignment_7_3_1() { return cUsageLimitsAssignment_7_3_1; }
		
		//UsageLimit
		public RuleCall getUsageLimitsUsageLimitParserRuleCall_7_3_1_0() { return cUsageLimitsUsageLimitParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RenewableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.Renewable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRenewableAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRenewableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValueKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDefaultValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDefaultValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDefaultValueEStringParserRuleCall_5_1_0 = (RuleCall)cDefaultValueAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescriptionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescriptionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_6_1_0 = (RuleCall)cDescriptionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cUnitKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cUnitAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cUnitEStringParserRuleCall_7_1_0 = (RuleCall)cUnitAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cValueTypeKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cValueTypeAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cValueTypeValueTypeEnumRuleCall_8_1_0 = (RuleCall)cValueTypeAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cLimitKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cLimitAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cLimitEDoubleParserRuleCall_9_1_0 = (RuleCall)cLimitAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cLinkedToKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cLinkedToAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final CrossReference cLinkedToFeatureCrossReference_10_2_0 = (CrossReference)cLinkedToAssignment_10_2.eContents().get(0);
		private final RuleCall cLinkedToFeatureEStringParserRuleCall_10_2_0_1 = (RuleCall)cLinkedToFeatureCrossReference_10_2_0.eContents().get(1);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cLinkedToAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final CrossReference cLinkedToFeatureCrossReference_10_3_1_0 = (CrossReference)cLinkedToAssignment_10_3_1.eContents().get(0);
		private final RuleCall cLinkedToFeatureEStringParserRuleCall_10_3_1_0_1 = (RuleCall)cLinkedToFeatureCrossReference_10_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cPeriodKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cPeriodAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cPeriodPeriodParserRuleCall_12_0 = (RuleCall)cPeriodAssignment_12.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Renewable returns Renewable:
		//    {Renewable}
		//    'Renewable'
		//    name=EString
		//    '{'
		//        ('value' value=EString)?
		//        ('defaultValue' defaultValue=EString)?
		//        ('description' description=EString)?
		//        ('unit' unit=EString)?
		//        ('valueType' valueType=ValueType)?
		//        ('limit' limit=EDouble)?
		//        ('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
		//        'period' period=Period
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Renewable}
		//'Renewable'
		//name=EString
		//'{'
		//    ('value' value=EString)?
		//    ('defaultValue' defaultValue=EString)?
		//    ('description' description=EString)?
		//    ('unit' unit=EString)?
		//    ('valueType' valueType=ValueType)?
		//    ('limit' limit=EDouble)?
		//    ('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
		//    'period' period=Period
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Renewable}
		public Action getRenewableAction_0() { return cRenewableAction_0; }
		
		//'Renewable'
		public Keyword getRenewableKeyword_1() { return cRenewableKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('value' value=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'value'
		public Keyword getValueKeyword_4_0() { return cValueKeyword_4_0; }
		
		//value=EString
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_4_1_0() { return cValueEStringParserRuleCall_4_1_0; }
		
		//('defaultValue' defaultValue=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'defaultValue'
		public Keyword getDefaultValueKeyword_5_0() { return cDefaultValueKeyword_5_0; }
		
		//defaultValue=EString
		public Assignment getDefaultValueAssignment_5_1() { return cDefaultValueAssignment_5_1; }
		
		//EString
		public RuleCall getDefaultValueEStringParserRuleCall_5_1_0() { return cDefaultValueEStringParserRuleCall_5_1_0; }
		
		//('description' description=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'description'
		public Keyword getDescriptionKeyword_6_0() { return cDescriptionKeyword_6_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_6_1() { return cDescriptionAssignment_6_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_6_1_0() { return cDescriptionEStringParserRuleCall_6_1_0; }
		
		//('unit' unit=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'unit'
		public Keyword getUnitKeyword_7_0() { return cUnitKeyword_7_0; }
		
		//unit=EString
		public Assignment getUnitAssignment_7_1() { return cUnitAssignment_7_1; }
		
		//EString
		public RuleCall getUnitEStringParserRuleCall_7_1_0() { return cUnitEStringParserRuleCall_7_1_0; }
		
		//('valueType' valueType=ValueType)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'valueType'
		public Keyword getValueTypeKeyword_8_0() { return cValueTypeKeyword_8_0; }
		
		//valueType=ValueType
		public Assignment getValueTypeAssignment_8_1() { return cValueTypeAssignment_8_1; }
		
		//ValueType
		public RuleCall getValueTypeValueTypeEnumRuleCall_8_1_0() { return cValueTypeValueTypeEnumRuleCall_8_1_0; }
		
		//('limit' limit=EDouble)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'limit'
		public Keyword getLimitKeyword_9_0() { return cLimitKeyword_9_0; }
		
		//limit=EDouble
		public Assignment getLimitAssignment_9_1() { return cLimitAssignment_9_1; }
		
		//EDouble
		public RuleCall getLimitEDoubleParserRuleCall_9_1_0() { return cLimitEDoubleParserRuleCall_9_1_0; }
		
		//('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'linkedTo'
		public Keyword getLinkedToKeyword_10_0() { return cLinkedToKeyword_10_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_10_1() { return cLeftParenthesisKeyword_10_1; }
		
		//linkedTo+=[Feature|EString]
		public Assignment getLinkedToAssignment_10_2() { return cLinkedToAssignment_10_2; }
		
		//[Feature|EString]
		public CrossReference getLinkedToFeatureCrossReference_10_2_0() { return cLinkedToFeatureCrossReference_10_2_0; }
		
		//EString
		public RuleCall getLinkedToFeatureEStringParserRuleCall_10_2_0_1() { return cLinkedToFeatureEStringParserRuleCall_10_2_0_1; }
		
		//( "," linkedTo+=[Feature|EString])*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//linkedTo+=[Feature|EString]
		public Assignment getLinkedToAssignment_10_3_1() { return cLinkedToAssignment_10_3_1; }
		
		//[Feature|EString]
		public CrossReference getLinkedToFeatureCrossReference_10_3_1_0() { return cLinkedToFeatureCrossReference_10_3_1_0; }
		
		//EString
		public RuleCall getLinkedToFeatureEStringParserRuleCall_10_3_1_0_1() { return cLinkedToFeatureEStringParserRuleCall_10_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_10_4() { return cRightParenthesisKeyword_10_4; }
		
		//'period'
		public Keyword getPeriodKeyword_11() { return cPeriodKeyword_11; }
		
		//period=Period
		public Assignment getPeriodAssignment_12() { return cPeriodAssignment_12; }
		
		//Period
		public RuleCall getPeriodPeriodParserRuleCall_12_0() { return cPeriodPeriodParserRuleCall_12_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class NonRenewableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.NonRenewable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNonRenewableAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cTrackableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cTrackableTrackableKeyword_1_0 = (Keyword)cTrackableAssignment_1.eContents().get(0);
		private final Keyword cNonRenewableKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDefaultValueKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDefaultValueAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDefaultValueEStringParserRuleCall_6_1_0 = (RuleCall)cDefaultValueAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDescriptionKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDescriptionAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_7_1_0 = (RuleCall)cDescriptionAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cUnitKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cUnitAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cUnitEStringParserRuleCall_8_1_0 = (RuleCall)cUnitAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cValueTypeKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cValueTypeAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cValueTypeValueTypeEnumRuleCall_9_1_0 = (RuleCall)cValueTypeAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cLimitKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cLimitAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cLimitEDoubleParserRuleCall_10_1_0 = (RuleCall)cLimitAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cLinkedToKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cLinkedToAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final CrossReference cLinkedToFeatureCrossReference_11_2_0 = (CrossReference)cLinkedToAssignment_11_2.eContents().get(0);
		private final RuleCall cLinkedToFeatureEStringParserRuleCall_11_2_0_1 = (RuleCall)cLinkedToFeatureCrossReference_11_2_0.eContents().get(1);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cLinkedToAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final CrossReference cLinkedToFeatureCrossReference_11_3_1_0 = (CrossReference)cLinkedToAssignment_11_3_1.eContents().get(0);
		private final RuleCall cLinkedToFeatureEStringParserRuleCall_11_3_1_0_1 = (RuleCall)cLinkedToFeatureCrossReference_11_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//NonRenewable returns NonRenewable:
		//    {NonRenewable}
		//    (trackable?='trackable')?
		//    'NonRenewable'
		//    name=EString
		//    '{'
		//        ('value' value=EString)?
		//        ('defaultValue' defaultValue=EString)?
		//        ('description' description=EString)?
		//        ('unit' unit=EString)?
		//        ('valueType' valueType=ValueType)?
		//        ('limit' limit=EDouble)?
		//        ('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{NonRenewable}
		//(trackable?='trackable')?
		//'NonRenewable'
		//name=EString
		//'{'
		//    ('value' value=EString)?
		//    ('defaultValue' defaultValue=EString)?
		//    ('description' description=EString)?
		//    ('unit' unit=EString)?
		//    ('valueType' valueType=ValueType)?
		//    ('limit' limit=EDouble)?
		//    ('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{NonRenewable}
		public Action getNonRenewableAction_0() { return cNonRenewableAction_0; }
		
		//(trackable?='trackable')?
		public Assignment getTrackableAssignment_1() { return cTrackableAssignment_1; }
		
		//'trackable'
		public Keyword getTrackableTrackableKeyword_1_0() { return cTrackableTrackableKeyword_1_0; }
		
		//'NonRenewable'
		public Keyword getNonRenewableKeyword_2() { return cNonRenewableKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//('value' value=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'value'
		public Keyword getValueKeyword_5_0() { return cValueKeyword_5_0; }
		
		//value=EString
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_5_1_0() { return cValueEStringParserRuleCall_5_1_0; }
		
		//('defaultValue' defaultValue=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'defaultValue'
		public Keyword getDefaultValueKeyword_6_0() { return cDefaultValueKeyword_6_0; }
		
		//defaultValue=EString
		public Assignment getDefaultValueAssignment_6_1() { return cDefaultValueAssignment_6_1; }
		
		//EString
		public RuleCall getDefaultValueEStringParserRuleCall_6_1_0() { return cDefaultValueEStringParserRuleCall_6_1_0; }
		
		//('description' description=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'description'
		public Keyword getDescriptionKeyword_7_0() { return cDescriptionKeyword_7_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_7_1() { return cDescriptionAssignment_7_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_7_1_0() { return cDescriptionEStringParserRuleCall_7_1_0; }
		
		//('unit' unit=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'unit'
		public Keyword getUnitKeyword_8_0() { return cUnitKeyword_8_0; }
		
		//unit=EString
		public Assignment getUnitAssignment_8_1() { return cUnitAssignment_8_1; }
		
		//EString
		public RuleCall getUnitEStringParserRuleCall_8_1_0() { return cUnitEStringParserRuleCall_8_1_0; }
		
		//('valueType' valueType=ValueType)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'valueType'
		public Keyword getValueTypeKeyword_9_0() { return cValueTypeKeyword_9_0; }
		
		//valueType=ValueType
		public Assignment getValueTypeAssignment_9_1() { return cValueTypeAssignment_9_1; }
		
		//ValueType
		public RuleCall getValueTypeValueTypeEnumRuleCall_9_1_0() { return cValueTypeValueTypeEnumRuleCall_9_1_0; }
		
		//('limit' limit=EDouble)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'limit'
		public Keyword getLimitKeyword_10_0() { return cLimitKeyword_10_0; }
		
		//limit=EDouble
		public Assignment getLimitAssignment_10_1() { return cLimitAssignment_10_1; }
		
		//EDouble
		public RuleCall getLimitEDoubleParserRuleCall_10_1_0() { return cLimitEDoubleParserRuleCall_10_1_0; }
		
		//('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
		public Group getGroup_11() { return cGroup_11; }
		
		//'linkedTo'
		public Keyword getLinkedToKeyword_11_0() { return cLinkedToKeyword_11_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_11_1() { return cLeftParenthesisKeyword_11_1; }
		
		//linkedTo+=[Feature|EString]
		public Assignment getLinkedToAssignment_11_2() { return cLinkedToAssignment_11_2; }
		
		//[Feature|EString]
		public CrossReference getLinkedToFeatureCrossReference_11_2_0() { return cLinkedToFeatureCrossReference_11_2_0; }
		
		//EString
		public RuleCall getLinkedToFeatureEStringParserRuleCall_11_2_0_1() { return cLinkedToFeatureEStringParserRuleCall_11_2_0_1; }
		
		//( "," linkedTo+=[Feature|EString])*
		public Group getGroup_11_3() { return cGroup_11_3; }
		
		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }
		
		//linkedTo+=[Feature|EString]
		public Assignment getLinkedToAssignment_11_3_1() { return cLinkedToAssignment_11_3_1; }
		
		//[Feature|EString]
		public CrossReference getLinkedToFeatureCrossReference_11_3_1_0() { return cLinkedToFeatureCrossReference_11_3_1_0; }
		
		//EString
		public RuleCall getLinkedToFeatureEStringParserRuleCall_11_3_1_0_1() { return cLinkedToFeatureEStringParserRuleCall_11_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_11_4() { return cRightParenthesisKeyword_11_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class PeriodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.Period");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPeriodAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPeriodKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cUnitKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cUnitAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cUnitTimeUnitEnumRuleCall_4_1_0 = (RuleCall)cUnitAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Period returns Period:
		//    {Period}
		//    'Period'
		//    '{'
		//        ('value' value=EInt)?
		//        ('unit' unit=TimeUnit)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Period}
		//'Period'
		//'{'
		//    ('value' value=EInt)?
		//    ('unit' unit=TimeUnit)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Period}
		public Action getPeriodAction_0() { return cPeriodAction_0; }
		
		//'Period'
		public Keyword getPeriodKeyword_1() { return cPeriodKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('value' value=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EInt
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_3_1_0() { return cValueEIntParserRuleCall_3_1_0; }
		
		//('unit' unit=TimeUnit)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'unit'
		public Keyword getUnitKeyword_4_0() { return cUnitKeyword_4_0; }
		
		//unit=TimeUnit
		public Assignment getUnitAssignment_4_1() { return cUnitAssignment_4_1; }
		
		//TimeUnit
		public RuleCall getUnitTimeUnitEnumRuleCall_4_1_0() { return cUnitTimeUnitEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	public class ValueTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.ValueType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNUMERICEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNUMERICNUMERICKeyword_0_0 = (Keyword)cNUMERICEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBOOLEANEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBOOLEANBOOLEANKeyword_1_0 = (Keyword)cBOOLEANEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTEXTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTEXTTEXTKeyword_2_0 = (Keyword)cTEXTEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ValueType returns ValueType:
		//                NUMERIC = 'NUMERIC' | BOOLEAN = 'BOOLEAN' | TEXT = 'TEXT';
		public EnumRule getRule() { return rule; }
		
		//NUMERIC = 'NUMERIC' | BOOLEAN = 'BOOLEAN' | TEXT = 'TEXT'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NUMERIC = 'NUMERIC'
		public EnumLiteralDeclaration getNUMERICEnumLiteralDeclaration_0() { return cNUMERICEnumLiteralDeclaration_0; }
		
		//'NUMERIC'
		public Keyword getNUMERICNUMERICKeyword_0_0() { return cNUMERICNUMERICKeyword_0_0; }
		
		//BOOLEAN = 'BOOLEAN'
		public EnumLiteralDeclaration getBOOLEANEnumLiteralDeclaration_1() { return cBOOLEANEnumLiteralDeclaration_1; }
		
		//'BOOLEAN'
		public Keyword getBOOLEANBOOLEANKeyword_1_0() { return cBOOLEANBOOLEANKeyword_1_0; }
		
		//TEXT = 'TEXT'
		public EnumLiteralDeclaration getTEXTEnumLiteralDeclaration_2() { return cTEXTEnumLiteralDeclaration_2; }
		
		//'TEXT'
		public Keyword getTEXTTEXTKeyword_2_0() { return cTEXTTEXTKeyword_2_0; }
	}
	public class TimeUnitElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "lsi.us.es.mis.xtext.MyPricingDsl.TimeUnit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSECEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSECSECKeyword_0_0 = (Keyword)cSECEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMINEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMINMINKeyword_1_0 = (Keyword)cMINEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cHOUREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cHOURHOURKeyword_2_0 = (Keyword)cHOUREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDAYEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDAYDAYKeyword_3_0 = (Keyword)cDAYEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cMONTHEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cMONTHMONTHKeyword_4_0 = (Keyword)cMONTHEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cYEAREnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cYEARYEARKeyword_5_0 = (Keyword)cYEAREnumLiteralDeclaration_5.eContents().get(0);
		
		//enum TimeUnit returns TimeUnit:
		//                SEC = 'SEC' | MIN = 'MIN' | HOUR = 'HOUR' | DAY = 'DAY' | MONTH = 'MONTH' | YEAR = 'YEAR';
		public EnumRule getRule() { return rule; }
		
		//SEC = 'SEC' | MIN = 'MIN' | HOUR = 'HOUR' | DAY = 'DAY' | MONTH = 'MONTH' | YEAR = 'YEAR'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SEC = 'SEC'
		public EnumLiteralDeclaration getSECEnumLiteralDeclaration_0() { return cSECEnumLiteralDeclaration_0; }
		
		//'SEC'
		public Keyword getSECSECKeyword_0_0() { return cSECSECKeyword_0_0; }
		
		//MIN = 'MIN'
		public EnumLiteralDeclaration getMINEnumLiteralDeclaration_1() { return cMINEnumLiteralDeclaration_1; }
		
		//'MIN'
		public Keyword getMINMINKeyword_1_0() { return cMINMINKeyword_1_0; }
		
		//HOUR = 'HOUR'
		public EnumLiteralDeclaration getHOUREnumLiteralDeclaration_2() { return cHOUREnumLiteralDeclaration_2; }
		
		//'HOUR'
		public Keyword getHOURHOURKeyword_2_0() { return cHOURHOURKeyword_2_0; }
		
		//DAY = 'DAY'
		public EnumLiteralDeclaration getDAYEnumLiteralDeclaration_3() { return cDAYEnumLiteralDeclaration_3; }
		
		//'DAY'
		public Keyword getDAYDAYKeyword_3_0() { return cDAYDAYKeyword_3_0; }
		
		//MONTH = 'MONTH'
		public EnumLiteralDeclaration getMONTHEnumLiteralDeclaration_4() { return cMONTHEnumLiteralDeclaration_4; }
		
		//'MONTH'
		public Keyword getMONTHMONTHKeyword_4_0() { return cMONTHMONTHKeyword_4_0; }
		
		//YEAR = 'YEAR'
		public EnumLiteralDeclaration getYEAREnumLiteralDeclaration_5() { return cYEAREnumLiteralDeclaration_5; }
		
		//'YEAR'
		public Keyword getYEARYEARKeyword_5_0() { return cYEARYEARKeyword_5_0; }
	}
	
	private final PricingElements pPricing;
	private final AddOnElements pAddOn;
	private final UsageLimitElements pUsageLimit;
	private final EStringElements pEString;
	private final EDoubleElements pEDouble;
	private final FeatureElements pFeature;
	private final PlanElements pPlan;
	private final ValueTypeElements eValueType;
	private final RenewableElements pRenewable;
	private final NonRenewableElements pNonRenewable;
	private final PeriodElements pPeriod;
	private final EIntElements pEInt;
	private final TimeUnitElements eTimeUnit;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyPricingDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPricing = new PricingElements();
		this.pAddOn = new AddOnElements();
		this.pUsageLimit = new UsageLimitElements();
		this.pEString = new EStringElements();
		this.pEDouble = new EDoubleElements();
		this.pFeature = new FeatureElements();
		this.pPlan = new PlanElements();
		this.eValueType = new ValueTypeElements();
		this.pRenewable = new RenewableElements();
		this.pNonRenewable = new NonRenewableElements();
		this.pPeriod = new PeriodElements();
		this.pEInt = new EIntElements();
		this.eTimeUnit = new TimeUnitElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("lsi.us.es.mis.xtext.MyPricingDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Pricing returns Pricing:
	//    {Pricing}
	//    'Pricing'
	//    '{'
	//        ('saasName' saasName=EString)?
	//        ('version' version=EString)?
	//        ('currency' currency=EString)?
	//        ('url' url=EString)?
	//        ('createdAt' createdAt=EString)?
	//        (plans+=Plan)*
	//        (addOns+=AddOn)*
	//    '}'
	//;
	public PricingElements getPricingAccess() {
		return pPricing;
	}
	
	public ParserRule getPricingRule() {
		return getPricingAccess().getRule();
	}
	
	//AddOn returns AddOn:
	//    {AddOn}
	//    'AddOn'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('price' price=EDouble)?
	//        ('usageLimits' '(' usageLimits+=[UsageLimit|EString] ( "," usageLimits+=[UsageLimit|EString])* ')' )?
	//        ('availableFor' '(' availableFor+=[Plan|EString] ( "," availableFor+=[Plan|EString])* ')' )?
	//        ('dependsOn' '(' dependsOn+=[AddOn|EString] ( "," dependsOn+=[AddOn|EString])* ')' )?
	//        ('excludes' '(' excludes+=[AddOn|EString] ( "," excludes+=[AddOn|EString])* ')' )?
	//        ('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
	//    '}';
	public AddOnElements getAddOnAccess() {
		return pAddOn;
	}
	
	public ParserRule getAddOnRule() {
		return getAddOnAccess().getRule();
	}
	
	//UsageLimit returns UsageLimit:
	//    Renewable | NonRenewable;
	public UsageLimitElements getUsageLimitAccess() {
		return pUsageLimit;
	}
	
	public ParserRule getUsageLimitRule() {
		return getUsageLimitAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EDouble returns ecore::EDouble:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return pEDouble;
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	//Feature returns Feature:
	//    {Feature}
	//    'Feature'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('value' value=EString)?
	//        ('expression' expression=EString)?
	//        ('serverExpression' serverExpression=EString)?
	//        ('defaultValue' defaultValue=EString)?
	//        ('valueType' valueType=ValueType)?
	//    '}';
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}
	
	//Plan returns Plan:
	//    {Plan}
	//    'Plan'
	//    name=EString
	//    '{'
	//        ('description' description=EString)?
	//        ('price' price=EDouble)?
	//        ('features' '{' features+=Feature ( "," features+=Feature)* '}' )?
	//        ('usageLimits' '{' usageLimits+=UsageLimit ( "," usageLimits+=UsageLimit)* '}' )?
	//    '}';
	public PlanElements getPlanAccess() {
		return pPlan;
	}
	
	public ParserRule getPlanRule() {
		return getPlanAccess().getRule();
	}
	
	//enum ValueType returns ValueType:
	//                NUMERIC = 'NUMERIC' | BOOLEAN = 'BOOLEAN' | TEXT = 'TEXT';
	public ValueTypeElements getValueTypeAccess() {
		return eValueType;
	}
	
	public EnumRule getValueTypeRule() {
		return getValueTypeAccess().getRule();
	}
	
	//Renewable returns Renewable:
	//    {Renewable}
	//    'Renewable'
	//    name=EString
	//    '{'
	//        ('value' value=EString)?
	//        ('defaultValue' defaultValue=EString)?
	//        ('description' description=EString)?
	//        ('unit' unit=EString)?
	//        ('valueType' valueType=ValueType)?
	//        ('limit' limit=EDouble)?
	//        ('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
	//        'period' period=Period
	//    '}';
	public RenewableElements getRenewableAccess() {
		return pRenewable;
	}
	
	public ParserRule getRenewableRule() {
		return getRenewableAccess().getRule();
	}
	
	//NonRenewable returns NonRenewable:
	//    {NonRenewable}
	//    (trackable?='trackable')?
	//    'NonRenewable'
	//    name=EString
	//    '{'
	//        ('value' value=EString)?
	//        ('defaultValue' defaultValue=EString)?
	//        ('description' description=EString)?
	//        ('unit' unit=EString)?
	//        ('valueType' valueType=ValueType)?
	//        ('limit' limit=EDouble)?
	//        ('linkedTo' '(' linkedTo+=[Feature|EString] ( "," linkedTo+=[Feature|EString])* ')' )?
	//    '}';
	public NonRenewableElements getNonRenewableAccess() {
		return pNonRenewable;
	}
	
	public ParserRule getNonRenewableRule() {
		return getNonRenewableAccess().getRule();
	}
	
	//Period returns Period:
	//    {Period}
	//    'Period'
	//    '{'
	//        ('value' value=EInt)?
	//        ('unit' unit=TimeUnit)?
	//    '}';
	public PeriodElements getPeriodAccess() {
		return pPeriod;
	}
	
	public ParserRule getPeriodRule() {
		return getPeriodAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum TimeUnit returns TimeUnit:
	//                SEC = 'SEC' | MIN = 'MIN' | HOUR = 'HOUR' | DAY = 'DAY' | MONTH = 'MONTH' | YEAR = 'YEAR';
	public TimeUnitElements getTimeUnitAccess() {
		return eTimeUnit;
	}
	
	public EnumRule getTimeUnitRule() {
		return getTimeUnitAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
