/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.ui.tests;

import com.google.inject.Injector;
import lsi.us.es.mis.xtext.pricing.ui.internal.PricingActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyPricingDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PricingActivator.getInstance().getInjector("lsi.us.es.mis.xtext.MyPricingDsl");
	}

}
