/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.parser.antlr;

import com.google.inject.Inject;
import lsi.us.es.mis.xtext.parser.antlr.internal.InternalMyPricingDslParser;
import lsi.us.es.mis.xtext.services.MyPricingDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyPricingDslParser extends AbstractAntlrParser {

	@Inject
	private MyPricingDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyPricingDslParser createParser(XtextTokenStream stream) {
		return new InternalMyPricingDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Pricing";
	}

	public MyPricingDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyPricingDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
