/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import com.google.inject.Inject

/**
 * Generador principal. Delega en los generadores TXT e YAML.
 * Patrón Delegation + Inyección de dependencias (slide 51-53).
 */
class MyPricingDslGenerator extends AbstractGenerator {

    // Dependency Injection
    @Inject MyPricingDslTxtGenerator genTxt

    @Inject MyPricingDslYAMLGenerator genYAML
    
    @Inject MyPricingDslHTMLGenerator genHTML
    
    

    override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
        genTxt.doGenerate(resource, fsa, context)
        genYAML.doGenerate(resource, fsa, context)
        genHTML.doGenerate(resource, fsa, context)
    }
}
