/*
 * generated by Xtext 2.30.0
 */
package lsi.us.es.mis.xtext.ui;

import com.google.inject.Injector;
import lsi.us.es.mis.xtext.pricing.ui.internal.PricingActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyPricingDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PricingActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PricingActivator activator = PricingActivator.getInstance();
		return activator != null ? activator.getInjector(PricingActivator.LSI_US_ES_MIS_XTEXT_MYPRICINGDSL) : null;
	}

}
